language: java

jdk:
  - oraclejdk8
  
addons:
  mariadb: '10.0'
  
services:
  - mysql
  - postgresql
  - mariadb

before_install:
  
  - mysql -u root -e 'CREATE DATABASE test_db;'
  - mysql -u root test_data < test/conf/travis-mysql.sql

  - psql -c 'CREATE DATABASE test_db;' -U postgres
  - psql -u postgres --password="" < test/conf/travis-pgsql.sql
  
    
script:
  - ant test
 
